# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Push to Google Could Platform

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: [ Run Tests ]
    types:
      - completed

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: go-simplebank

    steps:
      - id: auth
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: gcloud auth configure-docker --quite

      - name: Push Docker Image to Container Registry (GCR)
        env:
          GIT_TAG: ${{ github.sha }}
        run: |
          docker tag $IMAGE_NAME:lastest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker tag $IMAGE_NAME:lastest gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:$GIT_TAG
