# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Push to Google Could Platform

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: [ Run Tests ]
    types:
      - completed

jobs:
  build-push-gcr:
    name: Build and Push to GCP
    runs-on: ubuntu-latest
    env:
      IMAGE_NAME: go-simplebank
      PROJECT_ID: graceful-matter-384419

    steps:
      - uses: actions/checkout@v3

      - id: auth
        name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.SERVICE_ACCOUNT_KEY }}

      - name: Set up GCP SDK
        uses: google-github-actions/setup-gcloud@v1

      - name: Build Docker Image
        run: docker build -t $IMAGE_NAME:latest .

      - name: Configure Docker Client
        run: | 
          gcloud auth configure-docker --quiet
          gcloud auth configure-docker us-west1-docker.pkg.dev --quiet

      - name: Push Docker Image to Container Registry (GCR)
        run: |
          docker tag $IMAGE_NAME:latest gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
          docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest

      - name: Push Docker Image to Artifact Registry
        run: |
          docker tag $IMAGE_NAME:latest us-west1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME:latest
          docker push us-west1-docker.pkg.dev/$PROJECT_ID/$IMAGE_NAME/$IMAGE_NAME:latest   
